points = read.csv("concentrations.csv", header=FALSE)
x_s = c(1:length(points$V1))
png("iM.png")
plot(x_s, points$V1, xlab = "steps", ylab="iM concentration")
dev.off()
png("aM.png")
plot(x_s, points$V2, xlab = "steps", ylab="aM concentration")
dev.off()
png("A1.png")
plot(x_s, points$V3, xlab = "steps", ylab="A1 concentration")
dev.off()
png("A5.png")
plot(x_s, points$V7, xlab = "steps", ylab="A5 concentration")
dev.off()
png("A10.png")
plot(x_s, points$V12, xlab = "steps", ylab="A10 concentration")
dev.off()
png("A20.png")
plot(x_s, points$V22, xlab = "steps", ylab="A20 concentration")
dev.off()
